# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  # Autoformat: Python code
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --target-version=py310
          - --target-version=py311

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black

  # Autoformat: markdown, yaml (but not helm templates)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        exclude: binderhub-service/templates/.*

  # Linting: Python code (see the file .flake8)
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        # Ignore style and complexity
        # E: style errors
        # W: style warnings
        # C: complexity
        #
        args:
          - --ignore=E,C,W

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
