# ref: https://jekyllrb.com/docs/configuration/options/
#
# We make use of this theme, and it is what makes title and description have
# meaning.
# ref: https://github.com/pages-themes/minimal
theme: jekyll-theme-minimal

title: BinderHub-Service's Helm chart repository
description: |
  This the human friendly view of the BinderHub-Service charts.
  The command line tool
  <code>helm</code> will interacts with <a href="index.yaml">index.yaml</a>.
