# When running tests, we use a local container registry to test pushing images
# to that can be reached from the build pods.
#
config:
  BinderHub:
    log_level: DEBUG
    use_registry: true
    image_prefix: localhost:5000/binderhub-service/
buildPodsRegistryCredentials:
  server: "http://localhost:5000"
  username: ""
  password: ""

service:
  type: NodePort
  nodePort: 30080
