# This schema (a JSONSchema in YAML format) is used to generate
# values.schema.json to be packaged with the Helm chart.
#
# This schema is also planned to be used by our documentation system to build
# the configuration reference section based on the description fields. See
# docs/source/conf.py for that logic in the future!
#
# We look to document everything we have default values for in values.yaml, but
# we don't look to enforce the perfect validation logic within this file.
#
# ref: https://helm.sh/docs/topics/charts/#schema-files
# ref: https://json-schema.org/learn/getting-started-step-by-step.html
#
$schema: http://json-schema.org/draft-07/schema#
type: object
additionalProperties: true
required:
  - global
properties:
  nameOverride:
    type: string
  fullnameOverride:
    type: string
  global:
    type: object
    additionalProperties: true
