{{ - if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "binderhub-service.binderhub.fullname" . }}-builder-network-policy
spec:
  podSelector:
    matchLabels:
      component: binderhub-build
  policyTypes:
    - Egress
  egress:
    # Allow access to everything except private IPs
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
    # Allow access to DNS
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              # This label is added to dns deployments across all cloud providers
              # no matter their type, core-dns or kube-dns.
              k8s-app: kube-dns
{{ - end }}