# General configuration
# -----------------------------------------------------------------------------
#
nameOverride: ""
fullnameOverride: ""
global: {}

# Deployment resource
# -----------------------------------------------------------------------------
#
image:
  repository: quay.io/2i2c/binderhub-service
  tag: "set-by-chartpress"

# RBAC resources
# -----------------------------------------------------------------------------
#
rbac:
  create: true

# ServiceAccount resource
# -----------------------------------------------------------------------------
#
serviceAccount:
  create: true
  name: ""

# Service resource
# -----------------------------------------------------------------------------
#
service:
  type: ClusterIP
  port: 80

# Ingress resource
# -----------------------------------------------------------------------------
#
ingress:
  enabled: false

# DaemonSet resource - docker-api
# -----------------------------------------------------------------------------
#
dockerApi:
  image:
    repository: docker.io/library/docker
    tag: "23.0.4-dind"
  securityContext:
    privileged: true
    runAsUser: 0
